title:            Kenneth Larsen
description:      Kenneth Larsen's website.
url:              https://kennethlarsen.github.io/hjemmesiden
baseurl:          /hjemmesiden
permalink:        /posts/:title
timezone:         Europe/Copenhagen
kramdown:
  hard_wrap: true
sass:
  sass_dir: assets
  style: :compressed
collections:
  notes:
    output: false
  pages:
    output: true
i18n:
  Travel: Rejse
  Animals: Dyr
  Taiwan: 台灣
  Books: Bøger
  Cook: Madlavning
  Plants: 植物
  24h: 今天
  Mails: 郵件
  Friends: 朋友