name: "Sync stories"

on:
  workflow_dispatch:
    inputs:
      filepath:
        description: "JSON file path for the data"
        type: string
        required: true
      filedata:
        description: "Stringify JSON data of the image"
        type: string
        required: true

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17.7

      - name: Run script
        run: node .github/workflows/scripts/images.js '${{ inputs.filepath }}' '${{ inputs.filedata }}'

      - name: Push changes
        run: |
          git config user.email 'bot@kennethlarsen.org'
          git config user.name 'kenneth [bot]'
          git add .
          git commit -m "Add photo from Apple shortcuts" || echo "Nothing to commit"
          git fetch origin main
          git push origin HEAD:main
